---
title: "Assignment 3"
author: "Grace Bianchi"
date: "2023-03-01"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(kableExtra)
library(purrr)
library(cowplot)
source("~/Desktop/UCSB/Second_Year/ESM_262/ESM_262_Examples/R/autopower.R")
```


Imagine with have 3 different car types - and we know how often each occurs:

* car A  mass 20000 kg, area 22 m^2^
* car B mass 65000 kg, area 30 m^2^
* car C mass 38000 kg area 22 m^2^
* car D mass 5000 kg 10 m^2^


```{r}
# generate a structure to store info on our possible cars
possible_cars = data.frame(name = c("A","B","C","D"),mass=c(10000,65000,38000,5000), area = c(22,30,22,10))

# first look at how results vary for mean speed say 100km/hr
speed_base = (80 * 0.277)

# add to the data structure
possible_cars$power = autopower(V=speed_base, A = possible_cars$area, m=possible_cars$mass)
```

```{r}
# use sample to generate a distribution of speeds
nsample = 200
#assume a log normal distribution of speeds with mean 80 km/hr, and standard deviation that is 10 km/hr 
mean_speed = log(80*0.277)
sd_log = log(10*0.277)
speeds = rlnorm(mean = mean_speed, sd = sd_log, n = nsample)

#summary(speeds)
plot(density(speeds), ylab="Distribution of Speeds in (m/s)")
```

## For loop method
 
```{r}
# create an empty data frame
power_all_loop = as.data.frame(matrix(nrow=length(speeds), ncol=nrow(possible_cars)))

for (i in 1:nrow(possible_cars)) {
  power_all_loop[,i] = autopower(A=possible_cars$area[i], m=possible_cars$mass[i], V=speeds)
}
# we can add column names
colnames(power_all_loop)=possible_cars$name

# for plotting sometimes its useful to turn columns in to rows
 power_loop_long <- power_all_loop %>% pivot_longer(cols=everything(), names_to="car", values_to="power")

```

## purrr:pmap method

```{r}
power_all_pmap = pmap(list(A = possible_cars$area, m=possible_cars$mass), autopower, V=speeds)
power_all_pmap = as.data.frame(power_all_pmap, col.names=possible_cars$name) 
power_all_pmap = power_all_pmap %>% pivot_longer(cols=everything(), names_to="car", values_to="power") 

power_pmap_summary <- power_all_pmap %>% 
  group_by(car) %>% 
    summarize(mean_power = mean(power, na.rm = TRUE),
              max_power = max(power, na.rm = TRUE))
kable(power_pmap_summary, col.names = c("Car", "Mean Power", "Max Power"),caption = "Mean and maximum power of cars using pmap method") %>% 
  kable_styling(full_width = F) %>% 
  kable_classic()

```

```{r}
power_loop_summary <- power_loop_long %>% 
  group_by(car) %>% 
    summarize(mean_power = mean(power, na.rm = TRUE),
              max_power = max(power, na.rm = TRUE))

kable(power_loop_summary, col.names = c("Car", "Mean Power", "Max Power"), caption = "Mean and maximum power of cars using for loop method") %>% 
  kableExtra::kable_classic() %>% 
  kable_styling(full_width = FALSE)

```


```{r}

g1 <- ggplot(data = power_loop_long, aes(x = car, y = power, group = car)) +
  geom_boxplot() +
  labs(title = "For loop")

g2<- ggplot(data = power_all_pmap, aes(x = car, y = power, group = car)) +
  geom_boxplot() +
  labs(title = "Pmap Method")

plot_grid(g1+g2)
```

